controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute


index:
    path: /123
    controller: App\Controller\Admin\DashboardController::index

analytics:
    path: /analytics
    controller: App\Controller\Admin\DashboardController::analytics

finance:
    path: /finance
    controller: App\Controller\Admin\DashboardController::finance

crypto:
    path: /crypto
    controller: App\Controller\Admin\DashboardController::crypto




app_chat:
    path: /apps/chat
    controller: App\Controller\Admin\AppsController::chat

app_mailbox:
    path: /apps/mailbox
    controller: App\Controller\Admin\AppsController::mailbox

app_todo_list:
    path: /apps/todolist
    controller: App\Controller\Admin\AppsController::todo_list

app_notes:
    path: /apps/notes
    controller: App\Controller\Admin\AppsController::notes

app_scrumboard:
    path: /apps/scrumboard
    controller: App\Controller\Admin\AppsController::scrumboard

app_contacts:
    path: /apps/contacts
    controller: App\Controller\Admin\AppsController::contacts

app_invoice_list:
    path: /apps/invoice/list
    controller: App\Controller\Admin\AppsController::invoice_list

app_invoice_add:
    path: /apps/invoice/add
    controller: App\Controller\Admin\AppsController::invoice_add

app_invoice_preview:
    path: /apps/invoice/preview
    controller: App\Controller\Admin\AppsController::invoice_preview

app_invoice_edit:
    path: /apps/invoice/edit
    controller: App\Controller\Admin\AppsController::invoice_edit

app_calendar:
    path: /apps/calendar
    controller: App\Controller\Admin\AppsController::calendar




ui_components_tabs:
    path: /components/tabs
    controller: App\Controller\Admin\UIController::ui_components_tabs

ui_components_accordions:
    path: /components/accordions
    controller: App\Controller\Admin\UIController::ui_components_accordions

ui_components_modals:
    path: /components/modals
    controller: App\Controller\Admin\UIController::ui_components_modals

ui_components_cards:
    path: /components/cards
    controller: App\Controller\Admin\UIController::ui_components_cards

ui_components_carousel:
    path: /components/carousel
    controller: App\Controller\Admin\UIController::ui_components_carousel

ui_components_countdown:
    path: /components/countdown
    controller: App\Controller\Admin\UIController::ui_components_countdown

ui_components_counter:
    path: /components/counter
    controller: App\Controller\Admin\UIController::ui_components_counter

ui_components_sweetalert:
    path: /components/sweetalert
    controller: App\Controller\Admin\UIController::ui_components_sweet_alert

ui_components_timeline:
    path: /components/timeline
    controller: App\Controller\Admin\UIController::ui_components_timeline

ui_components_notifications:
    path: /components/notifications
    controller: App\Controller\Admin\UIController::ui_components_notifications

ui_components_media_object:
    path: /components/media-object
    controller: App\Controller\Admin\UIController::ui_components_media_object

ui_components_list_group:
    path: /components/list-group
    controller: App\Controller\Admin\UIController::ui_components_list_group

ui_components_pricing_table:
    path: /components/pricing-table
    controller: App\Controller\Admin\UIController::ui_components_pricing

ui_components_lightbox:
    path: /components/lightbox
    controller: App\Controller\Admin\UIController::ui_components_lightbox




ui_elements_alerts:
    path: /elements/alerts
    controller: App\Controller\Admin\UIController::elements_alerts

ui_elements_avatar:
    path: /elements/avatar
    controller: App\Controller\Admin\UIController::elements_avatar

ui_elements_badges:
    path: /elements/badges
    controller: App\Controller\Admin\UIController::elements_badges

ui_elements_breadcrumbs:
    path: /elements/breadcrumbs
    controller: App\Controller\Admin\UIController::elements_breadcrumbs

ui_elements_buttons:
    path: /elements/buttons
    controller: App\Controller\Admin\UIController::elements_buttons

ui_elements_buttons_group:
    path: /elements/buttons-group
    controller: App\Controller\Admin\UIController::elements_button_group

ui_elements_color_library:
    path: /elements/color-library
    controller: App\Controller\Admin\UIController::elements_color_library

ui_elements_dropdown:
    path: /elements/dropdown
    controller: App\Controller\Admin\UIController::elements_dropdown

ui_elements_infobox:
    path: /elements/infobox
    controller: App\Controller\Admin\UIController::elements_infobox

ui_elements_jumbotron:
    path: /elements/jumbotron
    controller: App\Controller\Admin\UIController::elements_jumbotron

ui_elements_loader:
    path: /elements/loader
    controller: App\Controller\Admin\UIController::elements_loader

ui_elements_pagination:
    path: /elements/pagination
    controller: App\Controller\Admin\UIController::elements_pagination

ui_elements_popovers:
    path: /elements/popovers
    controller: App\Controller\Admin\UIController::elements_popovers

ui_elements_progress_bar:
    path: /elements/progress-bar
    controller: App\Controller\Admin\UIController::elements_progress_bar

ui_elements_search:
    path: /elements/search
    controller: App\Controller\Admin\UIController::elements_search

ui_elements_tooltips:
    path: /elements/tooltips
    controller: App\Controller\Admin\UIController::elements_tooltips

ui_elements_treeview:
    path: /elements/treeview
    controller: App\Controller\Admin\UIController::elements_treeview

ui_elements_typography:
    path: /elements/typography
    controller: App\Controller\Admin\UIController::elements_typography




charts:
    path: /charts
    controller: App\Controller\Admin\UIController::charts

widgets:
    path: /widgets
    controller: App\Controller\Admin\UIController::widgets

font_icons:
    path: /font-icons
    controller: App\Controller\Admin\UIController::font_icons

drag_and_drop:
    path: /dragndrop
    controller: App\Controller\Admin\UIController::drag_and_drop


tables:
    path: /tables
    controller: App\Controller\Admin\TablesController::tables

datatables_advanced:
    path: /datatables/advanced
    controller: App\Controller\Admin\TablesController::datatables_advanced

datatables_alt_pagination:
    path: /datatables/alt-pagination
    controller: App\Controller\Admin\TablesController::datatables_alt_pagination

datatables_basic:
    path: /datatables/basic
    controller: App\Controller\Admin\TablesController::datatables_basic

datatables_checkbox:
    path: /datatables/checkbox
    controller: App\Controller\Admin\TablesController::datatables_checkbox

datatables_clone_header:
    path: /datatables/clone-header
    controller: App\Controller\Admin\TablesController::datatables_clone_header

datatables_column_chooser:
    path: /datatables/column-chooser
    controller: App\Controller\Admin\TablesController::datatables_column_chooser

datatables_export:
    path: /datatables/export
    controller: App\Controller\Admin\TablesController::datatables_export

datatables_multi_column:
    path: /datatables/multi-column
    controller: App\Controller\Admin\TablesController::datatables_multi_column

datatables_multiple_tables:
    path: /datatables/multiple-tables
    controller: App\Controller\Admin\TablesController::datatables_multiple_tables

datatables_order_sorting:
    path: /datatables/order-sorting
    controller: App\Controller\Admin\TablesController::datatables_order_sorting

datatables_range_search:
    path: /datatables/range-search
    controller: App\Controller\Admin\TablesController::datatables_range_search

datatables_skin:
    path: /datatables/skin
    controller: App\Controller\Admin\TablesController::datatables_skin

datatables_sticky_header:
    path: /datatables/sticky-header
    controller: App\Controller\Admin\TablesController::datatables_sticky_header




forms_basic:
    path: /forms/basic
    controller: App\Controller\Admin\FormsController::forms_basic

forms_input_group:
    path: /forms/input-group
    controller: App\Controller\Admin\FormsController::forms_input_group

forms_layouts:
    path: /forms/layouts
    controller: App\Controller\Admin\FormsController::forms_layouts

forms_validation:
    path: /forms/validation
    controller: App\Controller\Admin\FormsController::forms_validation

forms_input_mask:
    path: /forms/input-mask
    controller: App\Controller\Admin\FormsController::forms_input_mask

forms_checkbox_radio:
    path: /forms/checkbox-radio
    controller: App\Controller\Admin\FormsController::forms_checkbox_radio

forms_select2:
    path: /forms/select2
    controller: App\Controller\Admin\FormsController::forms_select2

forms_touchspin:
    path: /forms/touchspin
    controller: App\Controller\Admin\FormsController::forms_touchspin

forms_switches:
    path: /forms/switches
    controller: App\Controller\Admin\FormsController::forms_switches

forms_wizards:
    path: /forms/wizards
    controller: App\Controller\Admin\FormsController::forms_wizards

forms_file_upload:
    path: /forms/file-upload
    controller: App\Controller\Admin\FormsController::forms_file_upload

forms_quill_editor:
    path: /forms/quill-editor
    controller: App\Controller\Admin\FormsController::forms_quill_editor

forms_markdown_editor:
    path: /forms/markdown-editor
    controller: App\Controller\Admin\FormsController::forms_markdown_editor

forms_date_picker:
    path: /forms/date-picker
    controller: App\Controller\Admin\FormsController::forms_date_picker

forms_clipboard:
    path: /forms/clipboard
    controller: App\Controller\Admin\FormsController::forms_clipboard



users_profile:
    path: /users/profile
    controller: App\Controller\Admin\UsersController::users_profile

users_account_settings:
    path: /users/user-account-settings
    controller: App\Controller\Admin\UsersController::users_account_settings




pages_knowledge_base:
    path: /pages/knowledge-base
    controller: App\Controller\Admin\PagesController::pages_knowledge_base

pages_contact_us_boxed:
    path: /pages/contact-us-boxed
    controller: App\Controller\Admin\PagesController::pages_contact_us_boxed

pages_contact_us_cover:
    path: /pages/contact-us-cover
    controller: App\Controller\Admin\PagesController::pages_contact_us_cover

pages_faq:
    path: /pages/faq
    controller: App\Controller\Admin\PagesController::pages_faq

pages_coming_soon_boxed:
    path: /pages/coming-soon-boxed
    controller: App\Controller\Admin\PagesController::pages_coming_soon_boxed

pages_coming_soon_cover:
    path: /pages/coming-soon-cover
    controller: App\Controller\Admin\PagesController::pages_coming_soon_cover

pages_error404:
    path: /pages/error404
    controller: App\Controller\Admin\PagesController::pages_error404

pages_error500:
    path: /pages/error500
    controller: App\Controller\Admin\PagesController::pages_error500

pages_error503:
    path: /pages/error503
    controller: App\Controller\Admin\PagesController::pages_error503

pages_maintenence:
    path: /pages/maintenence
    controller: App\Controller\Admin\PagesController::pages_maintenence






auth_boxed_signin:
    path: /auth/boxed-signin
    controller: App\Controller\Admin\AuthController::auth_boxed_signin

auth_boxed_signup:
    path: /auth/boxed-signup
    controller: App\Controller\Admin\AuthController::auth_boxed_signup

auth_boxed_lockscreen:
    path: /auth/boxed-lockscreen
    controller: App\Controller\Admin\AuthController::auth_boxed_lockscreen

auth_boxed_password_reset:
    path: /auth/boxed-password-reset
    controller: App\Controller\Admin\AuthController::auth_boxed_password_reset

auth_cover_login:
    path: /auth/cover-login
    controller: App\Controller\Admin\AuthController::auth_cover_login

auth_cover_register:
    path: /auth/cover-register
    controller: App\Controller\Admin\AuthController::auth_cover_register

auth_cover_lockscreen:
    path: /auth/cover-lockscreen
    controller: App\Controller\Admin\AuthController::auth_cover_lockscreen

auth_cover_password_reset:
    path: /auth/cover-password-reset
    controller: App\Controller\Admin\AuthController::auth_cover_password_reset

